<a href="https://colab.research.google.com/github/pramodreddypandiri/oAuth/blob/main/DA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd

In [11]:
covid_df = pd.read_csv('/covid19_italy_region.csv')
#type(covid_df)
covid_df.head()

,SNo,Date,Country,RegionCode,RegionName,Latitude,Longitude,HospitalizedPatients,IntensiveCarePatients,TotalHospitalizedPatients,HomeConfinement,CurrentPositiveCases,NewPositiveCases,Recovered,Deaths,TotalPositiveCases,TestsPerformed
0,0,2020-02-24T18:00:00,ITA,13,Abruzzo,42.351222,13.398438,0,0,0,0,0,0,0,0,0,NaN
1,1,2020-02-24T18:00:00,ITA,17,Basilicata,40.639471,15.805148,0,0,0,0,0,0,0,0,0,NaN
2,2,2020-02-24T18:00:00,ITA,18,Calabria,38.905976,16.594402,0,0,0,0,0,0,0,0,0,NaN
3,3,2020-02-24T18:00:00,ITA,15,Campania,40.839566,14.250850,0,0,0,0,0,0,0,0,0,NaN
4,4,2020-02-24T18:00:00,ITA,8,Emilia-Romagna,44.494367,11.341721,10,2,12,6,18,18,0,0,18,NaN

In [19]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6027 entries, 0 to 6026
Data columns (total 16 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   SNo                        6027 non-null   int64
 1   Date                       6027 non-null   object
 2   Country                    6027 non-null   object
 3   RegionCode                 6027 non-null   int64
 4   RegionName                 6027 non-null   object
 5   Latitude                   6027 non-null   float64
 6   Longitude                  6027 non-null   float64
 7   HospitalizedPatients       6027 non-null   int64
 8   IntensiveCarePatients      6027 non-null   int64
 9   TotalHospitalizedPatients  6027 non-null   int64
 10  HomeConfinement            6027 non-null   int64
 11  CurrentPositiveCases       6027 non-null   int64
 12  NewPositiveCases           6027 non-null   int64
 13  Recovered                  6027 non-null   int64
 14  Deaths                     6027 non-null   int64
 15  TotalPositiveCases         6027 non-null   int64
dtypes: float64(2), int64(11), object(3)
memory usage: 753.5+ KB

In [21]:
covid_df.describe()

,SNo,RegionCode,Latitude,Longitude,HospitalizedPatients,IntensiveCarePatients,TotalHospitalizedPatients,HomeConfinement,CurrentPositiveCases,NewPositiveCases,Recovered,Deaths,TotalPositiveCases
count,6027.000000,6027.000000,6027.000000,6027.000000,6027.000000,6027.000000,6027.000000,6027.000000,6027.000000,6027.000000,6027.000000,6027.000000,6027.00000
mean,3013.000000,11.857143,43.046293,12.225955,509.093579,55.892318,564.985897,5722.911399,6287.897296,286.885847,9337.852829,1474.370665,17100.12361
std,1739.989368,6.274319,2.488987,2.659168,1272.731157,134.957979,1403.362341,15892.768789,16804.884786,818.450458,20551.265039,3365.190225,36934.67627
min,0.000000,1.000000,38.115697,7.320149,0.000000,0.000000,0.000000,0.000000,0.000000,-229.000000,0.000000,0.000000,0.00000
25%,1506.500000,7.000000,41.125596,11.121231,16.000000,1.000000,17.000000,139.000000,168.000000,4.000000,734.000000,98.000000,1383.50000
50%,3013.000000,12.000000,43.616760,12.388247,93.000000,9.000000,106.000000,743.000000,905.000000,31.000000,2840.000000,389.000000,4613.00000
75%,4519.500000,17.000000,45.434905,13.768136,384.500000,46.000000,434.000000,3057.000000,3735.000000,159.500000,8450.500000,1102.500000,15304.00000
max,6026.000000,22.000000,46.499335,16.867367,12077.000000,1381.000000,13328.000000,155066.000000,164406.000000,11489.000000,289706.000000,23024.000000,429109.00000

In [22]:
covid_df.columns

Index(['SNo', 'Date', 'Country', 'RegionCode', 'RegionName', 'Latitude',
       'Longitude', 'HospitalizedPatients', 'IntensiveCarePatients',
       'TotalHospitalizedPatients', 'HomeConfinement', 'CurrentPositiveCases',
       'NewPositiveCases', 'Recovered', 'Deaths', 'TotalPositiveCases'],
      dtype='object')

In [23]:
covid_df.shape

(6027, 16)

In [26]:
type(covid_df['RegionCode'][:10])

pandas.core.series.Series

In [30]:
print(covid_df.at[10
            , 'RegionCode'])

14

In [31]:
covid_df.Latitude

0       42.351222
1       40.639471
2       38.905976
3       40.839566
4       44.494367
          ...
6022    38.115697
6023    43.769231
6024    43.106758
6025    45.737503
6026    45.434905
Name: Latitude, Length: 6027, dtype: float64

In [33]:
covid_df.loc[243]

SNo                                          243
Date                         2020-03-06T17:00:00
Country                                      ITA
RegionCode                                    22
RegionName                           P.A. Trento
Latitude                               46.068935
Longitude                              11.121231
HospitalizedPatients                           4
IntensiveCarePatients                          0
TotalHospitalizedPatients                      4
HomeConfinement                                6
CurrentPositiveCases                          10
NewPositiveCases                               3
Recovered                                      0
Deaths                                         0
TotalPositiveCases                            10
Name: 243, dtype: object

In [35]:
covid_df.sample(10)

,SNo,Date,Country,RegionCode,RegionName,Latitude,Longitude,HospitalizedPatients,IntensiveCarePatients,TotalHospitalizedPatients,HomeConfinement,CurrentPositiveCases,NewPositiveCases,Recovered,Deaths,TotalPositiveCases
3605,3605,2020-08-13T17:00:00,ITA,16,Puglia,41.125596,16.867367,46,2,48,228,276,16,3979,554,4809
3823,3823,2020-08-24T17:00:00,ITA,17,Basilicata,40.639471,15.805148,2,0,2,68,70,0,404,28,502
2767,2767,2020-07-04T17:00:00,ITA,19,Sicilia,38.115697,13.362357,15,2,17,121,138,3,2674,282,3094
4691,4691,2020-10-04T17:00:00,ITA,3,Lombardia,45.466794,9.190347,296,39,335,9026,9361,314,81733,16971,108065
2455,2455,2020-06-19T17:00:00,ITA,2,Valle d'Aosta,45.737503,7.320149,4,0,4,0,4,0,1041,146,1191
4664,4664,2020-10-03T17:00:00,ITA,18,Calabria,38.905976,16.594402,36,2,38,520,558,24,1386,100,2044
1475,1475,2020-05-04T17:00:00,ITA,6,Friuli Venezia Giulia,45.649435,13.768136,130,4,134,916,1050,4,1727,299,3076
2491,2491,2020-06-21T17:00:00,ITA,1,Piemonte,45.073274,7.680687,356,19,375,1638,2013,26,25177,4051,31241
1663,1663,2020-05-13T17:00:00,ITA,8,Emilia-Romagna,44.494367,11.341721,1165,123,1288,5214,6502,50,16572,3905,26979
4190,4190,2020-09-10T17:00:00,ITA,21,P.A. Bolzano,46.499335,11.356624,8,0,8,231,239,20,2506,292,3037